# Usa una imagen base que incluya Java y Maven
FROM maven:3.8.4-openjdk-11-slim AS build

# Copia el código fuente y los archivos de configuración
COPY . /app
WORKDIR /app

# Compila el proyecto con Maven
RUN mvn clean install

# Define el comando de inicio de tu aplicación
CMD ["java", "-jar", "target/demo.jar"]